[package]
name = "rusting-wave-function"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
image = "0.25.6"
rand = "0.9.1"
roxmltree = "0.18.0"
strum = "0.27.1"
strum_macros = "0.27.1"
